name: 'PR Checks'
description: 'custom conditions on pull requests'
inputs:
  GITHUB_TOKEN: 
    description: 'github token'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: custom checks
      shell: bash
      run: npx danger ci
      env:
        DANGER_GITHUB_API_TOKEN: ${{ inputs.GITHUB_TOKEN }}
