name: 'PR Checks'
description: 'custom conditions on pull requests'
inputs:
  GITHUB_TOKEN: 
    description: 'github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: custom checks
      shell: bash
      run: npx danger ci
      working-directory: ${{ github.action_path }}
      env:
        DANGER_GITHUB_API_TOKEN: ${{ inputs.GITHUB_TOKEN }}
